const DATA = (module.exports = {});
DATA["Beer"] = [
    {
        uid: "cf42484a-7350-43ca-a6ec-16b3ca2b0702",
        brand: "Samuel Adams",
        name: "Bell’s Expedition",
        style: "Belgian And French Ale",
        hop: "TriplePearl",
        yeast: "3711 - French Saison",
        malts: "Carapils",
        ibu: "19 IBU",
        alcohol: "6.4%",
        blg: "5.1°Blg"
    },
    {
        uid: "5162699a-2003-4f4f-969f-418ee32a6c8d",
        brand: "Patagonia",
        name: "Duvel",
        style: "Amber Hybrid Beer",
        hop: "Chinook",
        yeast: "1007 - German Ale",
        malts: "Rye malt",
        ibu: "96 IBU",
        alcohol: "3.5%",
        blg: "17.3°Blg"
    },
    {
        uid: "767c6ac0-3b04-4466-a7c8-18ecf3cf1670",
        brand: "Sapporo",
        name: "Hercules Double IPA",
        style: "Belgian And French Ale",
        hop: "Chinook",
        yeast: "3711 - French Saison",
        malts: "Carapils",
        ibu: "52 IBU",
        alcohol: "4.6%",
        blg: "11.6°Blg"
    },
    {
        uid: "2ffe0964-7898-44fb-aa12-f0454a1b6916",
        brand: "Fosters",
        name: "Oak Aged Yeti Imperial Stout",
        style: "Scottish And Irish Ale",
        hop: "Olympic",
        yeast: "3787 - Trappist High Gravity",
        malts: "Wheat mal",
        ibu: "72 IBU",
        alcohol: "5.7%",
        blg: "12.0°Blg"
    },
    {
        uid: "c508f7b2-6daf-4ddd-bb47-502648e656ff",
        brand: "Becks",
        name: "Delirium Noctorum",
        style: "Belgian Strong Ale",
        hop: "Willamette",
        yeast: "1332 - Northwest Ale",
        malts: "Munich",
        ibu: "77 IBU",
        alcohol: "7.8%",
        blg: "10.6°Blg"
    },
    {
        uid: "eef024fd-addb-4bd3-9fa4-5fd8882a2fc3",
        brand: "Red Stripe",
        name: "Bourbon County Stout",
        style: "Light Lager",
        hop: "Perle",
        yeast: "3724 - Belgian Saison",
        malts: "Caramel",
        ibu: "45 IBU",
        alcohol: "4.7%",
        blg: "13.5°Blg"
    },
    {
        uid: '9e3e3b54-b255-43f6-bdea-1d007421cbf2',
        brand: 'BudLight',
        name: 'Double Bastard Ale',
        style: 'Light Hybrid Beer',
        hop: 'Bullion',
        yeast: '2565 - Kölsch',
        malts: 'Pale',
        ibu: '52 IBU',
        alcohol: '5.4%',
        blg: '10.2°Blg'
      },
      {
        uid: '42a4cc3d-5694-484e-8781-10404294b530',
        brand: 'Becks',
        name: 'Racer 5 India Pale Ale, Bear Republic Bre',
        style: 'Porter',
        hop: 'Perle',
        yeast: '1968 - London ESB Ale',
        malts: 'Carapils',
        ibu: '65 IBU',
        alcohol: '4.9%',
        blg: '15.0°Blg'
      },
      {
        uid: '643e0644-dd98-4447-a47f-643506c7be0f',
        brand: 'Miller Draft',
        name: 'Maudite',
        style: 'Smoke-flavored',
        hop: 'Newport',
        yeast: '1098 - British Ale',
        malts: 'Wheat mal',
        ibu: '19 IBU',
        alcohol: '5.8%',
        blg: '17.0°Blg'
      },
      {
        uid: '38c0b621-fec4-48cb-a98a-316de4a4cea7',
        brand: 'Hoegaarden',
        name: 'Maharaj',
        style: 'Dark Lager',
        hop: 'TriplePearl',
        yeast: '1272 - American Ale II',
        malts: 'Munich',
        ibu: '57 IBU',
        alcohol: '9.3%',
        blg: '14.6°Blg'
      },
      {
        uid: '7fb3fcc3-e628-4be3-b4fa-965c2b9bcd08',
        brand: 'Fosters',
        name: 'Brooklyn Black',
        style: 'Amber Hybrid Beer',
        hop: 'Bullion',
        yeast: '3763 - Roeselare Ale Blend',
        malts: 'Vienna',
        ibu: '82 IBU',
        alcohol: '4.4%',
        blg: '10.0°Blg'
      },
      {
        uid: '8f23c588-f2fa-43bd-9e4a-29a640cccba9',
        brand: 'Becks',
        name: 'Péché Mortel',
        style: 'Amber Hybrid Beer',
        hop: 'Mt. Rainier',
        yeast: '1214 - Belgian Abbey',
        malts: 'Chocolate',
        ibu: '26 IBU',
        alcohol: '4.4%',
        blg: '10.4°Blg'
      },
      {
        uid: '7a047973-e2d0-4813-8a98-83062d3e2272',
        brand: 'Paulaner',
        name: 'Founders Kentucky Breakfast',
        style: 'Bock',
        hop: 'Golding',
        yeast: '2278 - Czech Pils',
        malts: 'Special roast',
        ibu: '40 IBU',
        alcohol: '3.3%',
        blg: '13.2°Blg'
      },
      {
        uid: '00980c37-862e-4352-9e04-714c65698aa0',
        brand: 'Corona Extra',
        name: 'Shakespeare Oatmeal',
        style: 'Scottish And Irish Ale',
        hop: 'Tettnang',
        yeast: '1450 - Dennys Favorite 50',
        malts: 'Black malt',
        ibu: '64 IBU',
        alcohol: '6.5%',
        blg: '11.7°Blg'
      },
      {
        uid: 'f1a23869-b6b0-40e4-a52e-202dddffc07e',
        brand: 'Pacifico',
        name: 'Oak Aged Yeti Imperial Stout',
        style: 'Porter',
        hop: 'Millennium',
        yeast: '2042 - Danish Lager',
        malts: 'Wheat mal',
        ibu: '43 IBU',
        alcohol: '5.8%',
        blg: '6.8°Blg'
      },
      {
        uid: '4e74c37c-13d8-49c2-ae75-5a424654fe2e',
        brand: 'Pabst Blue Ribbon',
        name: 'Westmalle Trappist Tripel',
        style: 'English Pale Ale',
        hop: 'Galena',
        yeast: '1450 - Dennys Favorite 50',
        malts: 'Vienna',
        ibu: '80 IBU',
        alcohol: '9.4%',
        blg: '18.4°Blg'
      },
      {
        uid: '1afa604a-c77e-4f6c-8a11-a52e0d3deadd',
        brand: 'Tsingtao',
        name: 'Brooklyn Black',
        style: 'Porter',
        hop: 'Cluster',
        yeast: '2124 - Bohemian Lager',
        malts: 'Chocolate malt',
        ibu: '95 IBU',
        alcohol: '2.1%',
        blg: '12.6°Blg'
      },
      {
        uid: 'a33dea91-7768-4af4-8d7c-c00113446be0',
        brand: 'Corona Extra',
        name: 'Pliny The Elder',
        style: 'Smoke-flavored',
        hop: 'Cascade',
        yeast: '2007 - Pilsen Lager',
        malts: 'Roasted barley',
        ibu: '20 IBU',
        alcohol: '8.6%',
        blg: '11.1°Blg'
      },
      {
        uid: 'f640908c-e575-412c-b36b-b110d41a0404',
        brand: 'Red Stripe',
        name: 'Sublimely Self-Righteous Ale',
        style: 'Pilsner',
        hop: 'Palisade',
        yeast: '2206 - Bavarian Lager',
        malts: 'Caramel',
        ibu: '85 IBU',
        alcohol: '9.2%',
        blg: '5.2°Blg'
      },
      {
        uid: 'e96fd955-e776-4660-96cb-c0fe383c2e24',
        brand: 'Patagonia',
        name: 'Edmund Fitzgerald Porter',
        style: 'Wood-aged Beer',
        hop: 'Tettnang',
        yeast: '2633 - Octoberfest Lager Blend',
        malts: 'Rye malt',
        ibu: '63 IBU',
        alcohol: '5.6%',
        blg: '7.1°Blg'
      },
      {
        uid: '500a67ef-14ac-4f43-8a5f-bb1a87f70464',
        brand: 'Dos Equis',
        name: 'Stone IPA',
        style: 'Wood-aged Beer',
        hop: 'Eroica',
        yeast: '2206 - Bavarian Lager',
        malts: 'Carapils',
        ibu: '37 IBU',
        alcohol: '7.6%',
        blg: '14.3°Blg'
      },
      {
        uid: 'cc75f11a-a80f-4f84-9f68-66074881ff4e',
        brand: 'Pabst Blue Ribbon',
        name: 'Hop Rod Rye',
        style: 'European Amber Lager',
        hop: 'Northern Brewer',
        yeast: '1007 - German Ale',
        malts: 'Special roast',
        ibu: '72 IBU',
        alcohol: '4.9%',
        blg: '13.1°Blg'
      },
      {
        uid: 'fe529f12-56e5-4ada-b3ab-535d9f3a9b7a',
        brand: 'Dos Equis',
        name: 'Dreadnaught IPA',
        style: 'Light Hybrid Beer',
        hop: 'Bullion',
        yeast: '3942 - Belgian Wheat',
        malts: 'Pale',
        ibu: '63 IBU',
        alcohol: '6.0%',
        blg: '13.4°Blg'
      },
      {
        uid: 'fe583e3e-90ed-4cbc-8d16-e54f1cd86380',
        brand: 'Lowenbrau',
        name: 'St. Bernardus Abt 12',
        style: 'Wood-aged Beer',
        hop: 'Mt. Hood',
        yeast: '2565 - Kölsch',
        malts: 'Carapils',
        ibu: '40 IBU',
        alcohol: '5.4%',
        blg: '14.8°Blg'
      },
      {
        uid: '950c7bf8-47a1-47ac-8a0f-cd9f11f2f4e8',
        brand: 'Corona Extra',
        name: 'Founders Kentucky Breakfast',
        style: 'Belgian Strong Ale',
        hop: 'Ultra',
        yeast: '1469 - West Yorkshire Ale',
        malts: 'Caramel',
        ibu: '53 IBU',
        alcohol: '9.2%',
        blg: '12.6°Blg'
      },
      {
        uid: 'a22bae4b-3a86-4b9d-b2d5-20f2b49fbd57',
        brand: 'Kirin',
        name: 'Trappistes Rochefort 10',
        style: 'Sour Ale',
        hop: 'Ahtanum',
        yeast: '3522 - Belgian Ardennes',
        malts: 'Vienna',
        ibu: '93 IBU',
        alcohol: '3.7%',
        blg: '18.2°Blg'
      },
      {
        uid: '6416c44a-e623-4060-89ef-9aeed034f864',
        brand: 'Coors lite',
        name: 'Alpha King Pale Ale',
        style: 'Vegetable Beer',
        hop: 'Millennium',
        yeast: '1010 - American Wheat',
        malts: 'Wheat mal',
        ibu: '21 IBU',
        alcohol: '4.7%',
        blg: '6.1°Blg'
      },
      {
        uid: '64ce4660-f36c-4553-bbb0-fc277d902c02',
        brand: 'Miller Draft',
        name: 'Sapporo Premium',
        style: 'Light Hybrid Beer',
        hop: 'Mt. Hood',
        yeast: '3724 - Belgian Saison',
        malts: 'Munich',
        ibu: '23 IBU',
        alcohol: '8.7%',
        blg: '14.4°Blg'
      },
      {
        uid: '1ddee1e6-9e43-4a33-bd8b-c5a8a15c4231',
        brand: 'Murphys',
        name: 'Hennepin',
        style: 'Bock',
        hop: 'Palisade',
        yeast: '5335 - Lactobacillus',
        malts: 'Rye malt',
        ibu: '21 IBU',
        alcohol: '6.5%',
        blg: '12.0°Blg'
      },
      {
        uid: '580b261a-53c1-46c5-849d-cf3cd0bdf1f9',
        brand: 'Stella Artois',
        name: 'Ten FIDY',
        style: 'Porter',
        hop: 'Fuggle',
        yeast: '2000 - Budvar Lager',
        malts: 'Victory',
        ibu: '56 IBU',
        alcohol: '5.4%',
        blg: '13.5°Blg'
      },
      {
        uid: '412e3152-1b10-4e00-a33b-772a980c77f1',
        brand: 'Birra Moretti',
        name: 'Alpha King Pale Ale',
        style: 'Vegetable Beer',
        hop: 'Summit',
        yeast: '2206 - Bavarian Lager',
        malts: 'Chocolate malt',
        ibu: '60 IBU',
        alcohol: '4.9%',
        blg: '17.0°Blg'
      },
      {
        uid: '5293a1de-ae8b-40b9-aa08-1aac360b1c55',
        brand: 'Fosters',
        name: 'Maudite',
        style: 'Scottish And Irish Ale',
        hop: 'Equinox',
        yeast: '2000 - Budvar Lager',
        malts: 'Chocolate malt',
        ibu: '79 IBU',
        alcohol: '7.4%',
        blg: '12.8°Blg'
      },
      {
        uid: '8472b76b-f318-468f-bb58-5192967f2aa7',
        brand: 'Hoegaarden',
        name: 'Orval Trappist Ale',
        style: 'Merican Ale',
        hop: 'TriplePearl',
        yeast: '3522 - Belgian Ardennes',
        malts: 'Wheat mal',
        ibu: '43 IBU',
        alcohol: '6.5%',
        blg: '14.9°Blg'
      },
      {
        uid: '9036d6c5-532c-4605-b71f-39ebf404c5e5',
        brand: 'Samuel Adams',
        name: 'Chimay Grande Réserve',
        style: 'Pilsner',
        hop: 'Yakima Gol',
        yeast: '3068 - Weihenstephan Weizen',
        malts: 'Roasted barley',
        ibu: '90 IBU',
        alcohol: '2.8%',
        blg: '10.9°Blg'
      },
      {
        uid: '7cc019e8-7b03-435d-b5a9-683981646d61',
        brand: 'Murphys',
        name: 'Schneider Aventinus',
        style: 'Vegetable Beer',
        hop: 'Ahtanum',
        yeast: '2042 - Danish Lager',
        malts: 'Carapils',
        ibu: '93 IBU',
        alcohol: '4.1%',
        blg: '6.5°Blg'
      },
      {
        uid: '89369490-58af-4e84-bcd3-2c1f53c2f596',
        brand: 'Delirium',
        name: 'Edmund Fitzgerald Porter',
        style: 'English Pale Ale',
        hop: 'Chinook',
        yeast: '2633 - Octoberfest Lager Blend',
        malts: 'Black malt',
        ibu: '89 IBU',
        alcohol: '3.4%',
        blg: '5.1°Blg'
      },
      {
        uid: '5f7a2dfa-f8ed-4b30-ac23-8b941f319e77',
        brand: 'Quimes',
        name: 'Stone Imperial Russian Stout',
        style: 'Stout',
        hop: 'Mt. Hood',
        yeast: '5526 - Brettanomyces lambicus',
        malts: 'Black malt',
        ibu: '42 IBU',
        alcohol: '6.9%',
        blg: '14.6°Blg'
      },
      {
        uid: 'c800f666-d5a3-4066-9fe2-b56bafc3879e',
        brand: 'Birra Moretti',
        name: 'Orval Trappist Ale',
        style: 'Porter',
        hop: 'Simcoe',
        yeast: '1332 - Northwest Ale',
        malts: 'Vienna',
        ibu: '32 IBU',
        alcohol: '9.5%',
        blg: '9.7°Blg'
      },
      {
        uid: '7b6e4a6e-570f-4510-bfb7-eeb73a9d6cac',
        brand: 'Murphys',
        name: 'Stone IPA',
        style: 'Dark Lager',
        hop: 'Eroica',
        yeast: '3522 - Belgian Ardennes',
        malts: 'Munich',
        ibu: '12 IBU',
        alcohol: '6.4%',
        blg: '14.4°Blg'
      },
      {
        uid: 'bebfe1da-8172-4c3b-8248-f89eae450f17',
        brand: 'Tsingtao',
        name: 'Orval Trappist Ale',
        style: 'German Wheat And Rye Beer',
        hop: 'Yakima Gol',
        yeast: '1214 - Belgian Abbey',
        malts: 'Munich',
        ibu: '73 IBU',
        alcohol: '9.1%',
        blg: '14.8°Blg'
      },
      {
        uid: '17a1e7b7-146a-4d45-b405-bfa064359f4c',
        brand: 'Tsingtao',
        name: 'Sierra Nevada Celebration Ale',
        style: 'Vegetable Beer',
        hop: 'Summit',
        yeast: '3056 - Bavarian Wheat Blend',
        malts: 'Vienna',
        ibu: '36 IBU',
        alcohol: '3.0%',
        blg: '5.1°Blg'
      },
      {
        uid: '4e2dd965-11b6-427e-b689-ffcd5b79dcd7',
        brand: 'Leffe',
        name: 'Celebrator Doppelbock',
        style: 'Vegetable Beer',
        hop: 'Bravo',
        yeast: '1099 - Whitbread Ale',
        malts: 'Roasted barley',
        ibu: '42 IBU',
        alcohol: '2.6%',
        blg: '11.1°Blg'
      },
      {
        uid: '752dbed5-3747-4ce5-b88a-987a76ea5256',
        brand: 'Harp',
        name: 'Founders Kentucky Breakfast',
        style: 'Vegetable Beer',
        hop: 'Vanguard',
        yeast: '1275 - Thames Valley Ale',
        malts: 'Vienna',
        ibu: '44 IBU',
        alcohol: '9.8%',
        blg: '5.7°Blg'
      },
      {
        uid: 'cdab6564-6693-45da-bf65-1b5412e04c53',
        brand: 'Heineken',
        name: 'Sierra Nevada Celebration Ale',
        style: 'Vegetable Beer',
        hop: 'Centennial',
        yeast: '3068 - Weihenstephan Weizen',
        malts: 'Chocolate malt',
        ibu: '74 IBU',
        alcohol: '3.5%',
        blg: '13.0°Blg'
      },
      {
        uid: 'a0e46e24-c940-4eb9-82a4-57f6dae394c3',
        brand: 'Red Stripe',
        name: 'Ruination IPA',
        style: 'Amber Hybrid Beer',
        hop: 'Mt. Rainier',
        yeast: '1335 - British Ale II',
        malts: 'Caramel',
        ibu: '25 IBU',
        alcohol: '5.5%',
        blg: '12.8°Blg'
      },
      {
        uid: 'a66d5202-90eb-4391-a3ad-63edf94a9098',
        brand: 'Rolling Rock',
        name: 'Oak Aged Yeti Imperial Stout',
        style: 'Strong Ale',
        hop: 'Comet',
        yeast: '2112 - California Lager',
        malts: 'Chocolate malt',
        ibu: '65 IBU',
        alcohol: '3.8%',
        blg: '14.9°Blg'
      },
      {
        uid: 'a6f68834-f42d-45ed-a26b-8324cb2975a6',
        brand: 'Birra Moretti',
        name: 'Weihenstephaner Hefeweissbier',
        style: 'Dark Lager',
        hop: 'Warrior',
        yeast: '2000 - Budvar Lager',
        malts: 'Black malt',
        ibu: '43 IBU',
        alcohol: '4.4%',
        blg: '19.2°Blg'
      },
      {
        uid: '1e69e720-27b0-401c-9e5b-e92c3d834522',
        brand: 'Samuel Adams',
        name: 'Bourbon County Stout',
        style: 'European Amber Lager',
        hop: 'Willamette',
        yeast: '3944 - Belgian Witbier',
        malts: 'Caramel',
        ibu: '59 IBU',
        alcohol: '7.1%',
        blg: '18.3°Blg'
      },
      {
        uid: 'a6f3625e-1c33-4776-9d51-fff309e843f0',
        brand: 'Amstel',
        name: 'Dreadnaught IPA',
        style: 'Smoke-flavored',
        hop: 'Eroica',
        yeast: '1099 - Whitbread Ale',
        malts: 'Roasted barley',
        ibu: '78 IBU',
        alcohol: '6.1%',
        blg: '10.3°Blg'
      },
      {
        uid: '40407d8b-4b7c-4f81-8363-72dd454751dc',
        brand: 'Red Stripe',
        name: 'Delirium Tremens',
        style: 'India Pale Ale',
        hop: 'Fuggle',
        yeast: '3724 - Belgian Saison',
        malts: 'Rye malt',
        ibu: '83 IBU',
        alcohol: '9.7%',
        blg: '13.1°Blg'
      },
      {
        uid: 'e4164fda-dfef-46ad-ab5b-6db0fc9ea856',
        brand: 'Sierra Nevada',
        name: 'Shakespeare Oatmeal',
        style: 'Bock',
        hop: 'Chinook',
        yeast: '3724 - Belgian Saison',
        malts: 'Caramel',
        ibu: '99 IBU',
        alcohol: '4.3%',
        blg: '8.1°Blg'
      },
      {
        uid: '8eaca11a-941d-4ba6-9ac9-a60bb7dafe39',
        brand: 'Becks',
        name: 'Trois Pistoles',
        style: 'Smoke-flavored',
        hop: 'Bullion',
        yeast: '3638 - Bavarian Wheat',
        malts: 'Munich',
        ibu: '34 IBU',
        alcohol: '8.2%',
        blg: '12.6°Blg'
      },
      {
        uid: '40635873-8c50-4c44-bbc9-7889f2e79d0c',
        brand: 'Quimes',
        name: 'Racer 5 India Pale Ale, Bear Republic Bre',
        style: 'Sour Ale',
        hop: 'Willamette',
        yeast: '3942 - Belgian Wheat',
        malts: 'Pale',
        ibu: '61 IBU',
        alcohol: '9.0%',
        blg: '15.8°Blg'
      },
      {
        uid: '72b83418-239f-44b3-942e-40c700a9f4e9',
        brand: 'Guinness',
        name: 'Founders Kentucky Breakfast',
        style: 'Bock',
        hop: 'Bitter Gold',
        yeast: '1056 - American Ale',
        malts: 'Caramel',
        ibu: '10 IBU',
        alcohol: '9.5%',
        blg: '5.4°Blg'
      },
      {
        uid: '32f64b78-cfc1-4324-b6a2-8788a370757e',
        brand: 'Corona Extra',
        name: 'Weihenstephaner Hefeweissbier',
        style: 'Light Hybrid Beer',
        hop: 'Equinox',
        yeast: '2565 - Kölsch',
        malts: 'Roasted barley',
        ibu: '65 IBU',
        alcohol: '4.2%',
        blg: '19.1°Blg'
      },
      {
        uid: '0e83f633-fb74-426c-8e1b-f37920dda160',
        brand: 'Quimes',
        name: 'Two Hearted Ale',
        style: 'Stout',
        hop: 'Millennium',
        yeast: '1214 - Belgian Abbey',
        malts: 'Roasted barley',
        ibu: '41 IBU',
        alcohol: '9.4%',
        blg: '7.0°Blg'
      },
      {
        uid: 'feb75cb8-bbe7-4f71-a153-e212132d7977',
        brand: 'Budweiser',
        name: 'Oaked Arrogant Bastard Ale',
        style: 'Sour Ale',
        hop: 'Comet',
        yeast: '3068 - Weihenstephan Weizen',
        malts: 'Carapils',
        ibu: '54 IBU',
        alcohol: '7.7%',
        blg: '16.5°Blg'
      },
      {
        uid: 'e2802776-c7ec-4999-9d53-b0afbd5dc165',
        brand: 'Becks',
        name: 'Schneider Aventinus',
        style: 'Fruit Beer',
        hop: 'Chinook',
        yeast: '3278 - Belgian Lambic Blend',
        malts: 'Munich',
        ibu: '59 IBU',
        alcohol: '9.4%',
        blg: '14.9°Blg'
      },
      {
        uid: 'd25edd07-eeee-4e52-b452-c7d6fe030d8d',
        brand: 'Carlsberg',
        name: 'Hennepin',
        style: 'Belgian And French Ale',
        hop: 'Northern Brewer',
        yeast: '3763 - Roeselare Ale Blend',
        malts: 'Pale',
        ibu: '21 IBU',
        alcohol: '2.1%',
        blg: '11.7°Blg'
      },
      {
        uid: 'b27e7807-8522-499c-9e31-70e45bf44626',
        brand: 'Sapporo',
        name: 'Racer 5 India Pale Ale, Bear Republic Bre',
        style: 'Bock',
        hop: 'Saaz',
        yeast: '2000 - Budvar Lager',
        malts: 'Wheat mal',
        ibu: '60 IBU',
        alcohol: '8.3%',
        blg: '10.6°Blg'
      },
      {
        uid: '9ceb2aaf-8e63-40cf-bf1c-540c0f7f6715',
        brand: 'Delirium',
        name: 'Double Bastard Ale',
        style: 'Dark Lager',
        hop: 'Bravo',
        yeast: '1388 - Belgian Strong Ale',
        malts: 'Caramel',
        ibu: '26 IBU',
        alcohol: '2.4%',
        blg: '16.4°Blg'
      },
      {
        uid: '55c97070-41bf-4e3e-89de-5c65a23ceef1',
        brand: 'Blue Moon',
        name: 'Ten FIDY',
        style: 'Light Hybrid Beer',
        hop: 'Glacier',
        yeast: '5335 - Lactobacillus',
        malts: 'Caramel',
        ibu: '86 IBU',
        alcohol: '9.0%',
        blg: '16.1°Blg'
      },
      {
        uid: 'd3683f99-6d22-48a5-af7d-76c99476c7c8',
        brand: 'Hoegaarden',
        name: 'Arrogant Bastard Ale',
        style: 'India Pale Ale',
        hop: 'Columbus',
        yeast: '1469 - West Yorkshire Ale',
        malts: 'Munich',
        ibu: '33 IBU',
        alcohol: '9.3%',
        blg: '9.8°Blg'
      },
      {
        uid: 'd1f654ab-ddc7-4778-8245-35716b9102d6',
        brand: 'Birra Moretti',
        name: 'Maharaj',
        style: 'Strong Ale',
        hop: 'Fuggle',
        yeast: '1084 - Irish Ale',
        malts: 'Carapils',
        ibu: '34 IBU',
        alcohol: '3.8%',
        blg: '13.2°Blg'
      },
      {
        uid: 'b2418a2e-eff2-48af-b07b-d2793a3edaf0',
        brand: 'Blue Moon',
        name: 'Sublimely Self-Righteous Ale',
        style: 'Strong Ale',
        hop: 'Brewer’s Gold',
        yeast: '2278 - Czech Pils',
        malts: 'Chocolate',
        ibu: '12 IBU',
        alcohol: '5.7%',
        blg: '5.9°Blg'
      },
      {
        uid: '85cd904f-39e6-4e75-a1c2-c9915336e32e',
        brand: 'Guinness',
        name: 'HopSlam Ale',
        style: 'Bock',
        hop: 'Santiam',
        yeast: '1056 - American Ale',
        malts: 'Wheat mal',
        ibu: '28 IBU',
        alcohol: '4.7%',
        blg: '8.7°Blg'
      },
      {
        uid: '1b9b59e3-4c8d-4189-9055-5e623cc0f0dd',
        brand: 'Coors lite',
        name: 'Hop Rod Rye',
        style: 'Belgian And French Ale',
        hop: 'Chelan',
        yeast: '3333 - German Wheat',
        malts: 'Special roast',
        ibu: '18 IBU',
        alcohol: '4.1%',
        blg: '7.1°Blg'
      },
      {
        uid: 'd793a57c-11cd-4b9b-8afc-5a6f896bd6ef',
        brand: 'Dos Equis',
        name: 'La Fin Du Monde',
        style: 'Pilsner',
        hop: 'Mt. Rainier',
        yeast: '2000 - Budvar Lager',
        malts: 'Chocolate',
        ibu: '60 IBU',
        alcohol: '3.7%',
        blg: '5.3°Blg'
      },
      {
        uid: 'a368fddb-f43c-49c3-a9bf-55ed7bc951ac',
        brand: 'Harp',
        name: 'Sierra Nevada Celebration Ale',
        style: 'English Brown Ale',
        hop: 'Tettnang',
        yeast: '1098 - British Ale',
        malts: 'Caramel',
        ibu: '72 IBU',
        alcohol: '3.0%',
        blg: '11.0°Blg'
      },
      {
        uid: '4ead1d9e-b77d-4cde-a7d5-ba5b9d6b3899',
        brand: 'Sierra Nevada',
        name: 'Oaked Arrogant Bastard Ale',
        style: 'Light Lager',
        hop: 'Tahoma',
        yeast: '2633 - Octoberfest Lager Blend',
        malts: 'Wheat mal',
        ibu: '44 IBU',
        alcohol: '9.8%',
        blg: '14.0°Blg'
      },
      {
        uid: '2ab412dc-31d8-4b62-a48a-8eaa3e1f7f2c',
        brand: 'Sapporo',
        name: 'Old Rasputin Russian Imperial Stout',
        style: 'European Amber Lager',
        hop: 'Liberty',
        yeast: '2007 - Pilsen Lager',
        malts: 'Chocolate malt',
        ibu: '61 IBU',
        alcohol: '4.3%',
        blg: '5.3°Blg'
      },
      {
        uid: '829a8805-fb10-4099-9f3d-569d3de67363',
        brand: 'Hoegaarden',
        name: 'Westmalle Trappist Tripel',
        style: 'Porter',
        hop: 'Yakima Gol',
        yeast: '3638 - Bavarian Wheat',
        malts: 'Munich',
        ibu: '88 IBU',
        alcohol: '5.3%',
        blg: '12.0°Blg'
      },
      {
        uid: '781d5230-4f64-4ec7-91d8-661c83fbdb05',
        brand: 'Stella Artois',
        name: 'Two Hearted Ale',
        style: 'Belgian Strong Ale',
        hop: 'Golding',
        yeast: '2124 - Bohemian Lager',
        malts: 'Wheat mal',
        ibu: '78 IBU',
        alcohol: '2.3%',
        blg: '9.9°Blg'
      },
      {
        uid: '78b3e096-4137-466c-bf8e-f8fa4506b51e',
        brand: 'Patagonia',
        name: 'Chimay Grande Réserve',
        style: 'Pilsner',
        hop: 'Ultra',
        yeast: '1056 - American Ale',
        malts: 'Caramel',
        ibu: '34 IBU',
        alcohol: '2.3%',
        blg: '18.8°Blg'
      },
      {
        uid: '8805a46d-114f-4d64-8e02-6ac39c79e7a9',
        brand: 'Guinness',
        name: 'La Fin Du Monde',
        style: 'Vegetable Beer',
        hop: 'Bravo',
        yeast: '2308 - Munich Lager',
        malts: 'Special roast',
        ibu: '71 IBU',
        alcohol: '2.7%',
        blg: '10.6°Blg'
      },
      {
        uid: 'b3987eff-3fdb-4e79-b5ac-1e95abc07594',
        brand: 'Samuel Adams',
        name: 'Founders Kentucky Breakfast',
        style: 'Vegetable Beer',
        hop: 'Saaz',
        yeast: '1099 - Whitbread Ale',
        malts: 'Chocolate malt',
        ibu: '70 IBU',
        alcohol: '4.2%',
        blg: '17.0°Blg'
      },
      {
        uid: '335fa760-364d-4603-aa37-6d20da9852c7',
        brand: 'Harp',
        name: 'Delirium Tremens',
        style: 'Smoke-flavored',
        hop: 'Summit',
        yeast: '3068 - Weihenstephan Weizen',
        malts: 'Vienna',
        ibu: '67 IBU',
        alcohol: '8.9%',
        blg: '13.5°Blg'
      },
      {
        uid: '71103a7c-e746-43cd-8770-87150ef43455',
        brand: 'Delirium',
        name: 'Founders Kentucky Breakfast',
        style: 'Light Hybrid Beer',
        hop: 'Tettnang',
        yeast: '5733 - Pediococcus',
        malts: 'Chocolate malt',
        ibu: '22 IBU',
        alcohol: '6.4%',
        blg: '15.3°Blg'
      },
      {
        uid: '33b05183-6738-4227-bdd2-ab6c8c1e154b',
        brand: 'Murphys',
        name: 'Sublimely Self-Righteous Ale',
        style: 'English Pale Ale',
        hop: 'Amarillo',
        yeast: '3522 - Belgian Ardennes',
        malts: 'Caramel',
        ibu: '33 IBU',
        alcohol: '8.8%',
        blg: '12.7°Blg'
      },
      {
        uid: '4921153b-a31f-4c60-af35-adcc20603b5e',
        brand: 'Stella Artois',
        name: 'St. Bernardus Abt 12',
        style: 'Light Hybrid Beer',
        hop: 'Willamette',
        yeast: '2000 - Budvar Lager',
        malts: 'Chocolate',
        ibu: '85 IBU',
        alcohol: '7.8%',
        blg: '10.5°Blg'
      },
      {
        uid: '910bcdfc-60f3-4fef-af27-45fe1175e458',
        brand: 'Rolling Rock',
        name: 'Founders Kentucky Breakfast',
        style: 'India Pale Ale',
        hop: 'Sorachi Ace',
        yeast: '1187 - Ringwood Ale',
        malts: 'Caramel',
        ibu: '14 IBU',
        alcohol: '8.7%',
        blg: '8.2°Blg'
      },
      {
        uid: 'a3fa2bcc-76de-49a5-8835-55b6c3156424',
        brand: 'Patagonia',
        name: 'Celebrator Doppelbock',
        style: 'Scottish And Irish Ale',
        hop: 'Bullion',
        yeast: '3942 - Belgian Wheat',
        malts: 'Caramel',
        ibu: '61 IBU',
        alcohol: '5.5%',
        blg: '12.7°Blg'
      },
      {
        uid: 'b7330c6f-1f50-47dd-b0ad-2df8ab97118a',
        brand: 'Heineken',
        name: 'Pliny The Elder',
        style: 'German Wheat And Rye Beer',
        hop: 'Columbus',
        yeast: '1214 - Belgian Abbey',
        malts: 'Chocolate',
        ibu: '29 IBU',
        alcohol: '3.7%',
        blg: '9.9°Blg'
      },
      {
        uid: '3a348db0-19af-4a3c-bdf2-086c97126856',
        brand: 'BudLight',
        name: 'Alpha King Pale Ale',
        style: 'Wood-aged Beer',
        hop: 'Warrior',
        yeast: '1335 - British Ale II',
        malts: 'Rye malt',
        ibu: '44 IBU',
        alcohol: '8.9%',
        blg: '14.0°Blg'
      },
      {
        uid: '37bd19e5-e50d-4ffb-87c7-66124eada82b',
        brand: 'Pacifico',
        name: 'Maharaj',
        style: 'English Pale Ale',
        hop: 'Centennial',
        yeast: '1010 - American Wheat',
        malts: 'Roasted barley',
        ibu: '58 IBU',
        alcohol: '10.0%',
        blg: '17.3°Blg'
      },
      {
        uid: 'f1770192-7037-4fc0-820c-bd737d513a05',
        brand: 'Pabst Blue Ribbon',
        name: 'Edmund Fitzgerald Porter',
        style: 'Merican Ale',
        hop: 'Horizon',
        yeast: '3278 - Belgian Lambic Blend',
        malts: 'Black malt',
        ibu: '68 IBU',
        alcohol: '6.2%',
        blg: '19.4°Blg'
      }
];

